import React from 'react';
import { browserHistory } from 'react-router';
import styles from './style.css';


export default class LoginPage extends React.Component {
  signUp() {
    browserHistory.push('/home');
  }

  render() {
    return (
      <div className={styles.content}>
        <p className={styles.lead}>Lorem ipsum dolor sit amet, in eleifend dolores lacinia at nibh, justo cras tellus erat laoreet, massa sed nulla faucibus lorem mauris vestibulum. Mauris sit feugiat aliquam, vivamus habitasse wisi. Vivamus mauris condimentum. Ut imperdiet amet. Sociis potenti gravida augue ac mauris, sed lobortis, diam eu tellus suspendisse cras in lacinia, amet nulla morbi at porta nunc pulvinar, ac mollis facilisi nec non nisi turpis. Tristique aliquet mi placerat, fusce urna nonummy penatibus, adipiscing semper iaculis orci non, eros egestas felis. Class mi. Odio tortor, gravida mi, ante donec scelerisque est nulla mauris. Id felis turpis aenean. Wisi donec vivamus ipsum adipiscing vel, pede volutpat lorem quis mauris lacus, enim pulvinar ante aenean morbi dignissim, lectus vel nec wisi id arcu, et dapibus id id sociis sollicitudin enim. Cras vel non congue non a sodales, id curabitur dapibus interdum bibendum.</p>
        <p className={styles.lead}>At lorem facilisis lorem a enim, nulla lectus, libero donec integer. At massa primis libero, cum amet nulla amet et consectetuer, nam senectus nunc fusce eu eu arcu, feugiat ante ante pulvinar, nec orci id aptent proin blandit dui. Molestie scelerisque tellus sem blandit, magna sed in. Luctus felis fermentum lobortis aliquip vitae, sit proin corrupti vivamus, dictumst gravida sagittis ut pellentesque suspendisse cras, sodales ac aliquam, quis conubia aenean quisque eu quis malesuada. Maecenas vestibulum, morbi dolor magna proin dui, suspendisse sed, wisi viverra adipiscing faucibus diam sagittis. Vulputate elit bibendum erat non posuere. Varius vel in amet ligula non iaculis. Elit nec, arcu proin eu posuere, ac conubia nam, arcu lorem leo, mauris nunc odio nulla.</p>
        <p className={styles.lead}>Malesuada rutrum odio eu duis odio, id sagittis consectetuer eu turpis, nam augue nulla nunc scelerisque mi ac. Quam aliquam pede curabitur suscipit lacus et, dui quis urna ipsum, nullam in sit nulla etiam. Sapiente dui nulla duis, nunc posuere in, duis in dictum porttitor sodales ut magna, turpis montes. Vel nisl, condimentum mauris ad nec porta, vitae placerat, pellentesque magna morbi ultrices nec vehicula placerat. Tincidunt neque, massa amet augue eget pellentesque ullamcorper lobortis, eu ullamcorper morbi, dapibus orci, integer tellus magna nunc. Metus at eget urna. Ut libero libero sed enim, odio aptent ligula rutrum felis, vitae lorem quas quam purus eget fringilla, morbi pellentesque leo in. Phasellus tincidunt id, sed vulputate elementum pellentesque nascetur auctor, dignissim pede, commodo sed et sed aliquam nunc. Et blandit. In aliquam nec, nec velit placerat eu pellentesque risus, etiam ac, natoque ornare. Eu eu et tempor est fusce, dui est ultricies consectetuer tempus ullamcorper rutrum, vitae pede, aenean neque lorem, tempus velit class mauris ultrices justo.</p>
        <p className={styles.lead}>Nunc gravida. Dui lacus id non, dignissimos dui eget wisi pharetra porttitor neque, necessitatibus urna nulla felis tincidunt, feugiat turpis vitae nam et. Vel sed magnis, vestibulum feugiat sed amet quis amet commodo, ornare ut augue sed nam porta, nibh nunc scelerisque vitae mi magna, nostra faucibus nonummy egestas convallis adipiscing. Quis eros et morbi, wisi sit suspendisse lacinia mollis vitae, nulla etiam volutpat ipsam, iaculis est. Dis nonummy fermentum blandit. Sed metus maecenas, duis in nisl ornare enim mollis, dui mollis sed pharetra vitae, sagittis nulla dictum mattis sed phasellus quis, ut vivamus dolor nullam lobortis. Wisi volutpat sit, nunc ipsum est vestibulum velit. Molestie sed mollis tristique, lorem vestibulum pellentesque libero, ligula pede neque lobortis id viverra. Fusce nibh orci ipsum ullamcorper cum, sed quis augue proin elit urna vivamus, vestibulum libero lacinia, ullam eros habitant neque auctor. Porta vestibulum nullam ipsum quis donec, id in wisi duis, volutpat a sunt ac lorem egestas, id maecenas. Nec vitae felis tellus justo. Ut velit cursus proin.</p>
      </div>
    );
  }
}
